{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "s3-encryption-proxy.certificateName" . }}
  labels:
    {{- include "s3-encryption-proxy.labels" . | nindent 4 }}
  {{- with .Values.certificate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ .Values.certificate.secretName | default (include "s3-encryption-proxy.certificateName" .) }}
  issuerRef:
    name: {{ .Values.certificate.issuer.name }}
    kind: {{ .Values.certificate.issuer.kind }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  usages:
    - digital signature
    - key encipherment
{{- end }}
