{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "s3-encryption-proxy.fullname" . }}
  labels:
    {{- include "s3-encryption-proxy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "s3-encryption-proxy.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- range .Values.networkPolicy.policyTypes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}
