apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-encryption-proxy.secretName" . }}
  labels:
    {{- include "s3-encryption-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.s3.accessKeyId }}
  access-key-id: {{ .Values.secrets.s3.accessKeyId | b64enc }}
  {{- end }}
  {{- if .Values.secrets.s3.secretKey }}
  secret-key: {{ .Values.secrets.s3.secretKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.gcp.serviceAccountKey }}
  gcp-credentials.json: {{ .Values.secrets.gcp.serviceAccountKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.aws.accessKeyId }}
  aws-access-key-id: {{ .Values.secrets.aws.accessKeyId | b64enc }}
  {{- end }}
  {{- if .Values.secrets.aws.secretAccessKey }}
  aws-secret-access-key: {{ .Values.secrets.aws.secretAccessKey | b64enc }}
  {{- end }}
